project_id = "jwxhstlayjjakzffxqzi"

[functions.create-mercadopago-payment]
verify_jwt = false

[functions.mercadopago-webhook]
verify_jwt = false

[functions.generate-receipt]
verify_jwt = false

[functions.donation-status]
verify_jwt = false
